export const vaultAbi = [
  {
    type: 'function',
    name: 'fundMilestone',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acknowledgeStart',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitWork',
    inputs: [
      { name: 'evidenceHash_', type: 'bytes32' },
      { name: 'evidenceURI_', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approveAndRelease',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestRevision',
    inputs: [{ name: 'reasonHash', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'dispute',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimAfterReview',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'refundExpired',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposeMutualCancel',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getConfig',
    inputs: [],
    outputs: [
      { name: 'clientAddr', type: 'address' },
      { name: 'contractorAddr', type: 'address' },
      { name: 'tokenAddr', type: 'address' },
      { name: 'amountVal', type: 'uint256' },
      { name: 'scopeHashVal', type: 'bytes32' },
      { name: 'metadataURIVal', type: 'string' },
      { name: 'submissionPeriodVal', type: 'uint64' },
      { name: 'reviewPeriodVal', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStatus',
    inputs: [],
    outputs: [
      { name: 'stateVal', type: 'uint8' },
      { name: 'fundedAtVal', type: 'uint64' },
      { name: 'submitDeadlineVal', type: 'uint64' },
      { name: 'submittedAtVal', type: 'uint64' },
      { name: 'reviewDeadlineVal', type: 'uint64' },
      { name: 'evidenceHashVal', type: 'bytes32' },
      { name: 'evidenceURIVal', type: 'string' },
      { name: 'revisionCountVal', type: 'uint32' },
      { name: 'clientCancelProposedVal', type: 'bool' },
      { name: 'contractorCancelProposedVal', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'MilestoneFunded',
    inputs: [
      { name: 'fundedAt', type: 'uint64', indexed: false },
      { name: 'submitDeadline', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WorkAcknowledged',
    inputs: [],
  },
  {
    type: 'event',
    name: 'WorkSubmitted',
    inputs: [
      { name: 'evidenceHash', type: 'bytes32', indexed: true },
      { name: 'evidenceURI', type: 'string', indexed: false },
      { name: 'submittedAt', type: 'uint64', indexed: false },
      { name: 'reviewDeadline', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RevisionRequested',
    inputs: [
      { name: 'reasonHash', type: 'bytes32', indexed: true },
      { name: 'revisionCount', type: 'uint32', indexed: false },
      { name: 'submitDeadline', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MilestoneDisputed',
    inputs: [],
  },
  {
    type: 'event',
    name: 'MilestoneApproved',
    inputs: [],
  },
  {
    type: 'event',
    name: 'FundsReleased',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'TimeoutReleased',
    inputs: [{ name: 'reviewDeadline', type: 'uint64', indexed: false }],
  },
  {
    type: 'event',
    name: 'MilestoneRefunded',
    inputs: [{ name: 'reason', type: 'uint8', indexed: false }],
  },
  {
    type: 'event',
    name: 'MutualCancelProposed',
    inputs: [{ name: 'proposer', type: 'address', indexed: true }],
  },
] as const

export const factoryAbi = [
  {
    type: 'function',
    name: 'createMilestone',
    inputs: [
      { name: 'contractor', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'scopeHash', type: 'bytes32' },
      { name: 'metadataURI', type: 'string' },
      { name: 'submissionPeriod', type: 'uint64' },
      { name: 'reviewPeriod', type: 'uint64' },
    ],
    outputs: [{ name: 'vault', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isVault',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'MilestoneCreated',
    inputs: [
      { name: 'vault', type: 'address', indexed: true },
      { name: 'client', type: 'address', indexed: true },
      { name: 'contractor', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'scopeHash', type: 'bytes32', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
      { name: 'submissionPeriod', type: 'uint64', indexed: false },
      { name: 'reviewPeriod', type: 'uint64', indexed: false },
    ],
  },
] as const
